export default Message;
declare class Message {
    constructor(client: any, data: any);
    _events(data: any): void;
    data: object;
    key: object | null;
    id: string | null | undefined;
    jid: string | null | undefined;
    isGroup: boolean;
    fromMe: boolean ;
    pushName: string | undefined;
    message: any;
    prefix: string | undefined;
    sender: string | undefined;
    user: string | null | undefined;
    timestamp: number | undefined;
    text: string | null | undefined | boolean;
    bot: boolean | undefined;
    mention: any;
    reply_message: boolean | {
        id: string | undefined;
        fromMe: boolean;
        sender: string;
        key: object;
        pushName: string | null | undefined;
        bot: boolean;
        text: string | null | undefined;
        image: boolean;
        video: boolean;
        audio: boolean;
        sticker: boolean;
        document: boolean;
        viewonce: boolean | undefined | null;
        ephemeral: boolean;
    } | undefined;
    edit(content: any): Promise<Message>;
    sendReply(content: any, options?: {}): Promise<Message>;
    react(emoji: any, opts?: {}): Promise<Message>;
    delete(): Promise<Message>;
    clearChat(): Promise<Message>;
    archiveChat(opts?: boolean): Promise<Message>;
    forward(jid: any, content: any, options?: {}): Promise<Message>;
    downloadAndSaveMedia(): Promise<Buffer<ArrayBufferLike>>;
    send(content: any, options?: {}): Promise<Message>;
}
import { Buffer } from 'buffer';
