export function handleAutoKick(conn: any, msg: any): void;
export function chatAi(msg: any, conn: any): Promise<void>;
export function chatBotReply(msg: any, conn: any): Promise<void>;
export function logMessages(rawMessage: any, conn: any): Promise<void>;
export function handleAntiDelete(conn: any, updates: any): Promise<void>;
export function handleAntiLink(conn: any, msg: any): Promise<void>;
export function handleViewOnce(msg: any, conn: any, __events: any): Promise<any>;
export function handleAntiWord(conn: any, msg: any): Promise<void>;
export function handleGroupParticipants(conn: any): void;
export function schedules(client: any): Promise<void>;
